export default {
  title: require('../assets/icons/title.png'),
  login: require('../assets/icons/icon_login.png'),
  rectangle: require('../assets/icons/rectangle.png'),
  close: require('../assets/icons/close.png'),
  dog: require('../assets/icons/dog.png'),
  edittext: require('../assets/icons/edittext.png'),
  editColor: require('../assets/icons/chromatic.png'),
  sortDow: require('../assets/icons/sortDow.png'),
  square: require('../assets/icons/square.png'),
  text: require('../assets/icons/text.png'),
  B: require('../assets/icons/B.png'),
  I: require('../assets/icons/I.png'),
  facebook: require('../assets/icons/facebook.png'),
  google: require('../assets/icons/google.png'),
  visibility: require('../assets/icons/visibility.png'),
  unvisibility: require('../assets/icons/unvisibility.png'),
  vehicle: require('../assets/icons/vehicle.png'),
  savefile: require('../assets/icons/savefile.png'),
  weather: require('../assets/icons/weather.png'),
};
