import {StyleSheet} from 'react-native';
export default styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},
  viewTopTab: {
    height: '15%',
    zIndex: 9999,
    backgroundColor: 'rgb(207,207,207)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  saveButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 45,
    height: 45,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: 'rgb(0,0,225)',
  },
  buttonTopTab: {
    height: 45,
    width: 130,
    marginRight: 15,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    backgroundColor: 'rgba(160,82,45,0.1)',
    borderColor: 'rgb(160,82,45)',
  },
  textTopTab: {
    fontWeight: 'bold',
    fontSize: 16,
    color: 'rgb(160,82,45)',
  },
  buttonText: {
    height: 45,
    width: 50,
    marginRight: 15,
    borderRadius: 5,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(160,82,45,0.1)',
    borderColor: 'rgb(160,82,45)',
  },
  viewItem: {
    backgroundColor: 'rgb(207,207,207)',
    width: '70%',
    height: '100%',
  },
  eachViewItem: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    width: '95%',
    height: 150,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 5,
  },
  viewColor: {
    backgroundColor: 'rgb(207,207,207)',
    width: '30%',
    height: '100%',
  },
  eachViewColor: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 3,
    width: 60,
    height: 60,
    borderRadius: 60,
  },
  listIcon: {
    width: '33%',
    backgroundColor: 'rgb(245,245,245)',
    zIndex: 9999,
    flexDirection: 'row',
  },
  viewBackgroundNameCard: {
    flex: 1,
    backgroundColor: 'grey',
    zIndex: 9999,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
